#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_
#include <driver/gpio.h>
#define AUDIO_INPUT_SAMPLE_RATE 16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX
#define AUDIO_I2S_MIC_GPIO_WS GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16
#define BUILTIN_LED_GPIO GPIO_NUM_48
#define BOOT_BUTTON_GPIO GPIO_NUM_0
// HMB | TEC DualEye: 0 = XiaoZhi baseline only, 1 = GC9D01 eyes enabled
#define HMB_DUALEYE_ENABLED 1
#define HMB_EYE_SCLK GPIO_NUM_11
#define HMB_EYE_MOSI GPIO_NUM_12
#define HMB_EYE_DC GPIO_NUM_13
#define HMB_EYE_CS_LEFT GPIO_NUM_14
#define HMB_EYE_CS_RIGHT GPIO_NUM_21 //18
#define HMB_EYE_RST_LEFT GPIO_NUM_43
#define HMB_EYE_RST_RIGHT GPIO_NUM_44
#endif
